// <auto-generated />
using System;
using FitnessTracker.Infrastructure.Persistence.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessTracker.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(FitnessTrackerSqlServerDbContext))]
    partial class FitnessTrackerSqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.ExerciseSpecialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exercise_specialization_id");

                    b.Property<Guid>("TrainingExerciseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_exercise_id");

                    b.Property<Guid>("TrainingSpecializationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_specialization_id");

                    b.HasKey("Id");

                    b.HasIndex("TrainingExerciseId");

                    b.HasIndex("TrainingSpecializationId");

                    b.ToTable("exercise_specialization", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.Partnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("partnership_id");

                    b.Property<Guid>("ClientAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("client_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("TrainerAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trainer_account_id");

                    b.HasKey("Id");

                    b.HasIndex("ClientAccountId");

                    b.HasIndex("TrainerAccountId");

                    b.ToTable("partnership", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.PersonalProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("personal_profile_id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("account_id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("personal_profile", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainerSpecialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trainer_specialization_id");

                    b.Property<Guid>("TrainerAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trainer_account_id");

                    b.Property<Guid>("TrainingSpecializationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_specialization_id");

                    b.HasKey("Id");

                    b.HasIndex("TrainerAccountId");

                    b.HasIndex("TrainingSpecializationId");

                    b.ToTable("trainer_specialization", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_exercise_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Publicity")
                        .HasColumnType("int")
                        .HasColumnName("publicity");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.ToTable("training_exercise", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_plan_id");

                    b.Property<Guid?>("ClientAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("client_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsPersonalPlan")
                        .HasColumnType("bit")
                        .HasColumnName("is_personal_plan");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ClientAccountId");

                    b.HasIndex("CreatedByAccountId");

                    b.ToTable("training_plan", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingPlanGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_plan_goal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal?>("TargetWeight")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("target_weight");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_plan_id");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("training_plan_goal", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_session_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TrainingPlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_plan_id");

                    b.HasKey("Id");

                    b.HasIndex("TrainingPlanId");

                    b.ToTable("training_session", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingSessionGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_session_goal_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<decimal?>("TargetLiftingWeight")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("target_lifting_weight");

                    b.Property<int?>("TargetReps")
                        .HasColumnType("int")
                        .HasColumnName("target_reps");

                    b.Property<int?>("TargetSets")
                        .HasColumnType("int")
                        .HasColumnName("target_sets");

                    b.Property<Guid>("TrainingExerciseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_exercise_id");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_session_id");

                    b.HasKey("Id");

                    b.HasIndex("TrainingExerciseId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("training_session_goal", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingSessionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_session_log_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_account_id");

                    b.Property<decimal?>("LiftedWeight")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("lifted_weight");

                    b.Property<int?>("RepsCompleted")
                        .HasColumnType("int")
                        .HasColumnName("reps_completed");

                    b.Property<int?>("SetsCompleted")
                        .HasColumnType("int")
                        .HasColumnName("sets_completed");

                    b.Property<Guid>("TrainingExerciseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_exercise_id");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_session_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.HasIndex("TrainingExerciseId");

                    b.HasIndex("TrainingSessionId");

                    b.ToTable("training_session_log", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingSpecialization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_specialization_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("training_specialization", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.WeightGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("weight_goal_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_account_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("target_date");

                    b.Property<decimal>("TargetWeight")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("target_weight");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.ToTable("weight_goal", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.WeightLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("weight_log_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByAccountId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_account_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("unit");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAccountId");

                    b.ToTable("weight_log", (string)null);
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.ExerciseSpecialization", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.TrainingExercise", "TrainingExercise")
                        .WithMany("ExerciseSpecializations")
                        .HasForeignKey("TrainingExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Domain.Entities.TrainingSpecialization", "TrainingSpecialization")
                        .WithMany("ExerciseSpecializations")
                        .HasForeignKey("TrainingSpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingExercise");

                    b.Navigation("TrainingSpecialization");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.Partnership", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.Account", "ClientAccount")
                        .WithMany("PartnershipsAsClient")
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Domain.Entities.Account", "TrainerAccount")
                        .WithMany("PartnershipsAsTrainer")
                        .HasForeignKey("TrainerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientAccount");

                    b.Navigation("TrainerAccount");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.PersonalProfile", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.Account", "Account")
                        .WithOne("PersonalProfile")
                        .HasForeignKey("FitnessTracker.Domain.Entities.PersonalProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainerSpecialization", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.Account", "TrainerAccount")
                        .WithMany("TrainerSpecializations")
                        .HasForeignKey("TrainerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Domain.Entities.TrainingSpecialization", "TrainingSpecialization")
                        .WithMany("TrainerSpecializations")
                        .HasForeignKey("TrainingSpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainerAccount");

                    b.Navigation("TrainingSpecialization");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingExercise", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.Account", "CreatedByAccount")
                        .WithMany("CreatedTrainingExercises")
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByAccount");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingPlan", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.Account", "ClientAccount")
                        .WithMany("AssignedTrainingPlans")
                        .HasForeignKey("ClientAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitnessTracker.Domain.Entities.Account", "CreatedByAccount")
                        .WithMany("CreatedTrainingPlans")
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientAccount");

                    b.Navigation("CreatedByAccount");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingPlanGoal", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingPlanGoals")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingSession", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.TrainingPlan", "TrainingPlan")
                        .WithMany("TrainingSessions")
                        .HasForeignKey("TrainingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingPlan");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingSessionGoal", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.TrainingExercise", "TrainingExercise")
                        .WithMany("TrainingSessionGoals")
                        .HasForeignKey("TrainingExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Domain.Entities.TrainingSession", "TrainingSession")
                        .WithMany("TrainingSessionGoals")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingExercise");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingSessionLog", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.Account", "CreatedByAccount")
                        .WithMany("CreatedTrainingSessionLogs")
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Domain.Entities.TrainingExercise", "TrainingExercise")
                        .WithMany("TrainingSessionLogs")
                        .HasForeignKey("TrainingExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Domain.Entities.TrainingSession", "TrainingSession")
                        .WithMany("TrainingSessionLogs")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAccount");

                    b.Navigation("TrainingExercise");

                    b.Navigation("TrainingSession");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.WeightGoal", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.Account", "CreatedByAccount")
                        .WithMany("WeightGoals")
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAccount");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.WeightLog", b =>
                {
                    b.HasOne("FitnessTracker.Domain.Entities.Account", "CreatedByAccount")
                        .WithMany("CreatedWeightLogs")
                        .HasForeignKey("CreatedByAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByAccount");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.Account", b =>
                {
                    b.Navigation("AssignedTrainingPlans");

                    b.Navigation("CreatedTrainingExercises");

                    b.Navigation("CreatedTrainingPlans");

                    b.Navigation("CreatedTrainingSessionLogs");

                    b.Navigation("CreatedWeightLogs");

                    b.Navigation("PartnershipsAsClient");

                    b.Navigation("PartnershipsAsTrainer");

                    b.Navigation("PersonalProfile");

                    b.Navigation("TrainerSpecializations");

                    b.Navigation("WeightGoals");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingExercise", b =>
                {
                    b.Navigation("ExerciseSpecializations");

                    b.Navigation("TrainingSessionGoals");

                    b.Navigation("TrainingSessionLogs");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingPlan", b =>
                {
                    b.Navigation("TrainingPlanGoals");

                    b.Navigation("TrainingSessions");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingSession", b =>
                {
                    b.Navigation("TrainingSessionGoals");

                    b.Navigation("TrainingSessionLogs");
                });

            modelBuilder.Entity("FitnessTracker.Domain.Entities.TrainingSpecialization", b =>
                {
                    b.Navigation("ExerciseSpecializations");

                    b.Navigation("TrainerSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
